### ISSUE TITLE
Parent element

### ISSUE THREAD

**Issue by durasj** [chromawoods/instaFilta#17]
I am trying to implement your filter and it is quite good but so far unusable for me. The problem is element with text is not my entire element but only child with text. It would be really good if I could choose closest parent element which should be hidden. I will be probably implement it myself and do a PR.

**Comment by chromawoods** [comment]
Not enitirely sure what you mean. Would it be possible for you to use sections for this? Something like this:

```
<parent class="instafilta-section">
  <child class="instafilta-target">searchable text</child>
  Some other content
  Some other content
  Some other content
</parent>
```

**Comment by durasj** [comment]
Yes, but I am already using sections. I would be better if I could choose if insta should hide element which was found or some parent (jquery closest function). Unfortunately, I decided to write my own search functionality specific for my use, because I think it would take me more time to modify your code.

**Comment by chromawoods** [comment]
I see. I am currently developing v2 of the plugin and I will make sure to include your feature in it. Not sure when that will be completed, though. :)

**Comment by durasj** [comment]
Thank you! It does not matter. I already implemented my own code but I will be willing to adapt your next version if I see you are maintaing this project. You are probably better coder than I am and less things I have to worry about ... ;)

**Comment by Mgamerz** [comment]
I too am looking for something to hide a containing parent element of the unmatched item. This library looked so promising compared to others... :(

**Comment by chromawoods** [comment]
@Mgamerz check out the instaFilta2 project, it has support for this.

**Comment by durasj** [comment]
Link to the instaFilta2 (separate repository, not a branch): https://github.com/chromawoods/instaFilta2
