### ISSUE TITLE
How to use the synonyms option?

### ISSUE THREAD

**Issue by sebaortiz** [chromawoods/instaFilta#3]
Hi, i´m traying to set the synonym option and i´m might be using in the wrong way. The í character is not recognizes it. How can i set it? Sorry for my bad english :(
Thanks in advance!

**Comment by chromawoods** [comment]
Hi! Yeah I can see now that the í character is missing, it should actually be included in the default list of synonyms but for some reason I forgot the lowercase í. I can probably fix it tonight or some time over the weekend. Stay tuned.
/Andreas

**Comment by chromawoods** [comment]
Check out the latest version, it should solve your problem. Closing issue.

**Comment by sebaortiz** [comment]
Amazing work @chromawoods . Gracias!
